services:
  postgres:
    image: postgres:17.2
    container_name: jod-postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jod

  redis:
    image: redis:latest
    container_name: jod-redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"